[package]
name = "cluLogKmsg"
version = "0.1.1"
authors = ["Денис Котляров <denis2005991@gmail.com>"]

[lib]
name = "cluLogKmsg"
path = "src/lib.rs"

[dependencies]
cluLog = { git = "https://github.com/clucompany/cluLog" }
